# Generated by Django 4.2.4 on 2023-08-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photopost',
            old_name='imagel1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='photopost',
            old_name='imagel2',
            new_name='image2',
        ),
    ]
